cdnrun/urls.py
from django.conf.urls import patterns, url

from . import views


urlpatterns = patterns(
    '',
    url('^$', views.IndexView.as_view(), name='cdnrun-index'),
    url('^json/$', views.json_data, name='cdnrun-json'),
    url('^(?P<pk>\d+)/$',
        views.CDNDetailView.as_view(), name='cdnrun-detail'),
    url('^(?P<cdn>\w+)/diff/$',
        views.DiffView.as_view(), name='cdnrun-cdn-diff'),
    url('^start-cdn-check/$', views.start_cdn_check,
        name='cdnrun-start_cdn_check'),
)

performance/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.views.generic import TemplateView

# from rest_framework import routers

from . import views
# from . import viewsets

admin.autodiscover()

# router = routers.DefaultRouter(trailing_slash=False)
# router.register(r'resources', viewsets.ResourceViewSet)
# router.register(r'tests', viewsets.TestRunViewSet)
# router.register(r'tags', viewsets.TagViewSet)

urlpatterns = patterns(
    '',
    url(r'^$', TemplateView.as_view(template_name='index.html'),
        name='ng-app'),
    url(r'^home/$', views.HomeView.as_view(), name='home'),
    url(r'^status/$', views.current_status, name='current_status'),

    url(r'^analyse/$', views.CompareView.as_view(), name='analyse'),
    url(r'^analyse/runs/$', views.CompareTestRunListView.as_view(),
        name='runs_analyse'),

    url(r'^resources/$', views.ResourceList.as_view(), name='resources'),
    url(r'^runs/$', views.TestRunList.as_view(), name='runs'),
    url(r'^tags/$', views.TagList.as_view(), name='tags'),
    url(r'^tags/(?P<slug>.*)/$', views.TaggedTestRun.as_view(), name='tags'),

    url(r'^resources/(?P<pk>\d+)/$', views.ResourceDetail.as_view(),
        name='resource'),
    url(r'^runs/(?P<pk>\d+)/$', views.TestRunDetail.as_view(), name='run'),
    url(r'^runs/clone/$', views.CloneRunView.as_view(), name='clone_run'),

    url(r'^resources/create/$', views.ResourceCreate.as_view(),
        name='resource_create'),
    url(r'^runs/create/$', views.TestRunCreate.as_view(), name='run_create'),

    url(r'^runs/(?P<pk>\d+)/polyrun/summary/(?P<page>.*)$',
        views.PolyrunSummaryView.as_view(), name='run-polyrun-summary'),
    url(r'^runs/(?P<pk>\d+)/state$', views.testrun_state, name='run-state'),
    url(r'^runs/(?P<pk>\d+)/diag_log/$', views.diag_log, name='diag_log'),
    url(r'^runs/(?P<pk>\d+)/rrd_files/$', views.rrd_files, name='rrd_files'),
    url(r'^runs/(?P<pk>\d+)/progress/$', views.progress_ts,
        name='run-progress'),
    url(r'^runs/(?P<pk>\d+)/dhcp-lps/$', views.dhcp_lps, name='dhcp-lps'),
    url(r'^runs/(?P<pk>\d+)/(?P<scr>\w+)/$', views.ScriptsFormView.as_view(),
        name='run_script'),

    url(r'^start-scheduled/$', views.start_scheduled, {'pk': 'all'},
        name='start_scheduled'),
    url(r'^start-scheduled/(?P<pk>\d+)/$', views.start_scheduled,
        name='start_scheduled'),

    url(r'^attachments/', include('attachments.urls')),
    url(r'^social_auth/', include('social.apps.django_app.urls',
                                  namespace='social')),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^cdn-status/', include('cdnrun.urls')),
    url(r'^calamaris/', include('rrtools.calamaris.urls')),
    # url(r'^eslog/', include('rrtools.eslog.urls')),

    url(r'^ng-last-modified/$', views.ng_last_modified),
    url(r'^current-user/$', views.current_user),
    url(r'^performance-summary', views.performance_summary),
    # url(r'^api/', include(router.urls)),
    # url(r'^api-auth/', include('rest_framework.urls',
    #                            namespace='rest_framework')),
)

if settings.DEBUG:
    import os
    from django.conf.urls.static import static

    NG_APP_ROOT = os.path.join(settings.NG_ROOT, 'app')
    NG_FONTS_ROOT = os.path.join(settings.NG_ROOT, 'fonts')
    NG_IMAGES_ROOT = os.path.join(settings.NG_ROOT, 'images')

    urlpatterns = urlpatterns + static(settings.MEDIA_URL,
                                       document_root=settings.MEDIA_ROOT)
    urlpatterns = urlpatterns + static('/app/', document_root=NG_APP_ROOT)
    urlpatterns = urlpatterns + static('/fonts/', document_root=NG_FONTS_ROOT)
    urlpatterns = urlpatterns + static('/images/', document_root=NG_IMAGES_ROOT)

performance/models.py
"""
Performance models
==================
"""

from datetime import datetime, timedelta
import os
import json
import logging
from collections import deque


from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from django.core.files import File
from django.contrib.contenttypes.models import ContentType
from django.core.urlresolvers import reverse
from django.core.cache import cache

from taggit.managers import TaggableManager

from attachments.models import Attachment
from jsonfield import JSONField
from performance import socketioclient
from polygraph.polyrun import Polyrun, check_progress as polyrun_progress
from remote.ssh import execute


logger = logging.getLogger('django')


class ResourceConst(object):
    IDLE = 0
    IN_USE = 10
    UNAVAILABLE = -1

    RESOURCE_STATUS = (
        (IDLE, 'Idle'),
        (IN_USE, 'In use'),
        (UNAVAILABLE, 'Unavailable'),
    )


class TestRunConst(object):
    WAITING = 0
    SCHEDULED = 5
    RUNNING = 10
    FAIL = 20
    STOPPED = 25
    SUCCESS = 30

    RUN_STATES = (
        (WAITING, 'Waiting'),
        (SCHEDULED, 'Scheduled'),
        (RUNNING, 'Running'),
        (SUCCESS, 'Successful'),
        (STOPPED, 'Stopped'),
        (FAIL, 'Failed'),
    )


class TestRunError(Exception):
    """
    """


class ResourceInUse(Exception):
    """
    """


def send_notification(status, data=None):
    """
    Send a notification via socket.io
    """
    try:
        with socketioclient.SocketIO('localhost', 8001) as sock:
            perf_sock = sock.define(socketioclient.BaseNamespace,
                                    '/performance')
            perf_sock.emit(status, data)
    except:
        logger.exception('send_notification')


class TimestampedModel(models.Model):
    title = models.CharField(max_length=300)
    created_by = models.ForeignKey(User)
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        abstract = True

    def __unicode__(self):
        return self.title


class Resource(TimestampedModel):
    ip_address = models.GenericIPAddressField(blank=True, null=True)
    rtype = models.CharField(blank=True, max_length=300, verbose_name='Type')
    description = models.TextField()
    state = models.IntegerField(choices=ResourceConst.RESOURCE_STATUS,
                                default=ResourceConst.IDLE)

    class Meta:
        ordering = ('ip_address', 'rtype', 'title')

    @models.permalink
    def get_absolute_url(self):
        return ('resource', (self.pk,))

    @property
    def status(self):
        return dict(ResourceConst.RESOURCE_STATUS).get(self.state)

    @property
    def status_icon(self):
        return {
            ResourceConst.IDLE: 'icon-off',
            ResourceConst.IN_USE: 'icon-spinner',
            ResourceConst.UNAVAILABLE: 'icon-ban-circle',
        }.get(self.state, ResourceConst.UNAVAILABLE)

    @property
    def idle(self):
        return self.state == ResourceConst.IDLE

    @property
    def in_use(self):
        return self.state == ResourceConst.IN_USE

    @property
    def unavailable(self):
        return self.state == ResourceConst.UNAVAILABLE

    def set_idle(self):
        if self.testrun_set.running().count() == 0:
            self.state = ResourceConst.IDLE
            self.save()

    def set_available(self):
        if self.testrun_set.running().count() > 0:
            self.state = ResourceConst.IN_USE
            self.save()
        else:
            self.set_idle()

    def set_unavailable(self):
        self.state = ResourceConst.UNAVAILABLE
        self.save()


class RunManager(models.Manager):
    def waiting(self):
        return self.get_queryset().filter(state=TestRunConst.WAITING)

    def scheduled(self):
        return self.get_queryset().filter(state=TestRunConst.SCHEDULED)

    def running(self):
        return self.get_queryset().filter(state=TestRunConst.RUNNING)

    def completed(self):
        return self.get_queryset().filter(state__gt=TestRunConst.RUNNING)

    def successful(self):
        return self.get_queryset().filter(state=TestRunConst.SUCCESS)

    def failed(self):
        return self.get_queryset().filter(state=TestRunConst.FAIL)


class TestRun(TimestampedModel):
    resources = models.ManyToManyField(Resource, blank=True)
    team = models.ManyToManyField(User, blank=True, related_name='team')

    description = models.TextField()

    started_on = models.DateTimeField(null=True, blank=True)
    completed_on = models.DateTimeField(null=True, blank=True)
    eta = models.DateTimeField(null=True, blank=True)
    estimated_days = models.FloatField(default=1.0)

    queue = models.PositiveIntegerField(null=True, blank=True)
    state = models.IntegerField(choices=TestRunConst.RUN_STATES,
                                default=TestRunConst.WAITING)

    inputs = JSONField(blank=True)
    outputs = JSONField(blank=True)

    script = models.CharField(blank=True, max_length=300)
    script_inputs = JSONField(blank=True)
    script_outputs = JSONField(blank=True)

    report = models.TextField(blank=True)

    objects = RunManager()
    tags = TaggableManager(blank=True)

    class Meta:
        ordering = ('-state', '-completed_on', '-started_on', 'queue')

    def __unicode__(self):
        return self.title

    @models.permalink
    def get_absolute_url(self):
        return ('run', (self.pk,))

    @property
    def status(self):
        return dict(TestRunConst.RUN_STATES).get(self.state)

    @property
    def waiting(self):
        return self.state == TestRunConst.WAITING

    @property
    def scheduled(self):
        return self.state == TestRunConst.SCHEDULED

    @property
    def ready_to_run(self):
        return self.state in (TestRunConst.WAITING, TestRunConst.SCHEDULED)

    @property
    def running(self):
        return self.state == TestRunConst.RUNNING

    @property
    def finished(self):
        return self.state not in (TestRunConst.WAITING, TestRunConst.RUNNING)

    @property
    def script_name(self):
        """
        Name of the script that is run for this test
        """
        if self.script:
            return self.script.split(':')[0]
        return None

    @property
    def script_id(self):
        """
        Celery task ID for the script
        """
        if self.script:
            return self.script.split(':')[-1]
        return None

    @property
    def cache_engine(self):
        """
        Get cache engine used in this run
        """
        return self.inputs.get('Cache engine')

    def set_inputs(self, script, task_id=None, inputs=None, eta=None):
        """
        Save script inputs

        :param script: script name
        :param task_id: celery task id
        :param inputs: inputs the for script
        :param eta: estimated time for task to be completed
        """
        self.script = '{}:{}'.format(script, task_id or '')
        self.script_inputs = inputs
        self.script_outputs = None
        self.eta = eta or datetime.now() + timedelta(days=self.estimated_days)
        self.save()

    def schedule_later(self):
        """
        Schedule the test run to run later
        """
        self.state = TestRunConst.SCHEDULED
        self.save()
        send_notification('refresh', {'url': self.get_absolute_url(),
                                      'id': self.pk})

    def start(self):
        """
        Start the test run

        :raises: :py:class:`performance.models.TestRunError`
            if its not waiting or required resource is busy
        """
        if not self.ready_to_run:
            raise TestRunError('Not waiting to be run')
        for resource in self.resources.all():
            if not resource.idle:
                raise ResourceInUse('{r.title} is "{r.status}"'
                                    .format(r=resource))
        self.state = TestRunConst.RUNNING
        self.started_on = datetime.now()
        self.save()
        for resource in self.resources.all():
            resource.state = ResourceConst.IN_USE
            resource.save()

        send_notification('refresh', {'url': self.get_absolute_url(),
                                      'id': self.pk})

    def stop(self, state):
        """
        Stop the test

        :raises: :py:class:`performance.models.TestRunError`
            if not running
        """
        if not self.running:
            raise TestRunError('Not running')
        self.state = state
        self.completed_on = datetime.now()
        self.save()
        for resource in self.resources.all():
            resource.set_idle()

        send_notification('refresh', {'url': self.get_absolute_url(),
                                      'id': self.pk})

        self.clear_cached_values('progress')
        self.clear_cached_values('progress-ts')

    def success(self, output=None):
        """
        Stop the test and mark it successful
        """
        self.script_outputs = output
        self.stop(TestRunConst.SUCCESS)
        self.attach_logs()
        self.update_params()

        from .runners import start_scheduled_run
        start_scheduled_run()
        send_notification('success')

    def fail(self):
        """
        Stop the test and mark it failed
        """
        self.stop(TestRunConst.FAIL)
        send_notification('fail')

    def force_stop(self):
        """
        Stop the test but do not mark it as fail
        """
        self.stop(TestRunConst.STOPPED)
        send_notification('fail')

    def reset(self):
        """
        Reset the test
        """
        self.state = TestRunConst.WAITING
        self.started_on = None
        self.completed_on = None
        self.eta = None
        self.script_outputs = ''
        self.save()

        for resource in self.resources.all():
            resource.set_idle()

        send_notification('refresh', {'url': self.get_absolute_url(),

performance/templates/performance/_polyrun_limitation.html
<div class="panel panel-danger">
    <div class="panel-heading">Caveats</div>
    <div class="panel-body">
        There are several things to consider
        when running a polygraph test.<br>

        Following are some known limitations of a polygraph test:
    </div>

    <ul class="list-group">
        <li class="list-group-item">
            To generate a repeatable traffic select <em>Yes</em> for
            <strong>Repeatable</strong>. Note that, a repeatable traffic
            requires selecting the same
            <strong>Recipe, Polyrig, Schedule type, Schedule value, Phase duration</strong>.
            It is also recommended to run such tests on empty CACHEbox.
        <li class="list-group-item list-group-item-warning">
            The number of phases generated by scheduler
            (i.e., Steps, Constant) should not be more than 12.
            If there is more than 12 phases in a single run,
            the report generation of the test will fail
            because of filename length limits.
            (The report contains HTML pages and
            the filename of those pages include the phase names)
        </li>
        <li class="list-group-item list-group-item-danger">
            A long constant phase run is not possible
            as polygraph keeps the test stats in memory
            for the whole phase.
            This can oom kill the polygraph clients.
        </li>
        <li class="list-group-item list-group-item-warning">
            To overcome the previous limitation,
            a constant phase is actually split into
            100 minutes smaller phases.
        </li>
        <li class="list-group-item list-group-item-danger">
            When setting the RPS value for the test
            please have a look at the optimum performance table
            at home page. The table shows known maximum RPS value
            for different models of CACHEbox.
        </li>
        <li class="list-group-item list-group-item-warning">
            Please keep in mind that Polyrig 2 is not
            as strong as Polyrig 1 setup.
        </li>
        <li class="list-group-item list-group-item-danger">
            Only explicit and bypass proxy works out of the box.
            For other modes, a network setup might be necessary.
        </li>
    </ul>
</div>

performance/templates/performance/_polyrun_result.html
{% load jsonify %}
{% if polyrun.outputs %}
    <div id="polyrun-output-json" class="hide">{{ polyrun.outputs|jsonify }}</div>
    <div class="panel paenl-default">
        <div class="panel-body">
            <div id="polyrun-output-graph"></div>
        </div>
    </div>
    <h3>Polyrun output</h3>
    <table class="table table-bordered table-striped table-hover">
        <thead>
            <tr>
                <th rowspan="2" class="text-right">Phase</th>
                <th colspan="2" class="text-center">RPS</th>
                <th colspan="2" class="text-center">BHR</th>
                <th colspan="2" class="text-center">DHR</th>
                <th colspan="2" class="text-center">Mbps</th>
                <th rowspan="2" class="text-right">Errors %</th>
            </tr>
            <tr>
                <th class="text-right">Measured</th>
                <th class="text-right">Offered</th>
                <th class="text-right">Measured</th>
                <th class="text-right">Offered</th>
                <th class="text-right">Measured</th>
                <th class="text-right">Offered</th>
                <th class="text-right">Measured</th>
                <th class="text-right">Offered</th>
            </tr>
        </thead>
        <tbody class="text-right">
            {% for row in polyrun.outputs %}
                <tr class="{% if row.errors > 0.1 %}danger{% elif row.errors > 0.01 %}warning{% endif %}">
                    <td>{{ row.phase }}</td>
                    <td>{{ row.rps.measured }}</td>
                    <td>
                        <small class="text-muted">{{ row.rps.offered }}</small>
                    </td>
                    <td>{{ row.bhr.measured }}</td>
                    <td>
                        <small class="text-muted">{{ row.bhr.offered }}</small>
                    </td>
                    <td>{{ row.dhr.measured }}</td>
                    <td>
                        <small class="text-muted">{{ row.dhr.offered }}</small>
                    </td>
                    <td>{{ row.mbps.measured }}</td>
                    <td>
                        <small class="text-muted">{{ row.mbps.offered }}</small>
                    </td>
                    <td>{{ row.errors }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <div class="btn-group">
        {% for phtml, ptitle in testrun.polyrun_htmls %}
            <a href="{{ phtml }}" class="btn polyrun-html btn-default">{{ ptitle }}</a>
        {% endfor %}
    </div>
{% endif %}
{% if polyrun.inputs %}
    <h3>Polyrun setup</h3>
    <table class="table table-striped table-hover table-bordered">
        {% for k, v in polyrun.inputs %}
            <tr>
                <th>{{ k }}</th>
                <td>{{ v|safe }}</td>
            </tr>
        {% endfor %}
    </table>
{% endif %}

performance/templates/performance/_run_description.html
{% load markup_tags performance_tags %}
<div class="panel panel-default">
    <div class="panel-heading"><h3 class="panel-title">Description</h3></div>
    <div class="panel-body">{{ testrun.description|apply_markup:'markdown' }}</div>
</div>
<div class="panel panel-default">
    <div class="panel-heading"><h3 class="panel-title">Report</h3></div>
    <div class="panel-body">{{ testrun.report|apply_markup:'markdown' }}</div>
</div>
<div class="panel panel-default">
    <div class="panel-heading"><h3 class="panel-title">Key Parameters</h3></div>
    <div class="panel-body">
        <div class="panel panel-info">
            <div class="panel-heading">
                <h3 class="panel-title">Control Parameters</h3>
            </div>
            <table class="table table-bordered table-striped params">
                {% for label, value in testrun.inputs.items %}
                    {% if value %}
                    <tr>
                        <th class="text-right">{{ label }}</th>
                        <td>{{ value|param_split_val }}</td>
                    </tr>
                    {% endif %}
                {% empty %}
                    <tr><td>No control parameter defined</td></tr>
                {% endfor %}
            </table>
        </div>
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">Output Parameters</h3>
            </div>
            <table class="table table-bordered table-striped params">
                {% for label, value in testrun.outputs.items %}
                    {% if value %}
                    <tr>
                        <th class="text-right">{{ label }}</th>
                        <td>{{ value|param_split_val }}</td>
                    </tr>
                    {% endif %}
                {% empty %}
                    <tr><td>No output parameter defined</td></tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>

performance/templates/performance/_run_sidebar.html
{% load attachments_tags performance_tags %}
{% if testrun.waiting %}
    <div class="panel panel-default">
        <div class="panel-heading"><h4 class="panel-title">Scripts</h4></div>
        <div class="panel-body">
            <ul class="list-unstyled script-list">
                {% for s in scripts %}
                    <li>
                        <div class="btn-group btn-group-justified">
                            <a class="btn btn-default" href="{% url 'run_script' testrun.pk s %}">{{ s|title }}</a>
                            <a class="btn btn-primary" href="{% url 'run_script' testrun.pk s %}">
                                <i class="icon-bolt"></i> Run
                            </a>
                        </div>
                    </li>
                {% endfor %}
            </ul>
            <form method="POST" class="text-center">
                {% csrf_token %}
                <input type="hidden" name="action" value="start" />
                <div class="btn-group">
                    <button type="submit" class="btn btn-default">Custom Run</button>
                </div>
            </form>
        </div>
    </div>
{% elif testrun.running %}
    <div class="panel panel-default">
        <div class="panel-body">
            <div id="progress-meter"></div>
            <div id="progress-ts"></div>
            <dl id="progress-status">
                {% for p in progress %}
                    <dt class="{{ p.title|tag_class }}">{{ p.title }}</dt>
                    <dd class="{{ p.title|tag_class }}">{{ p.message }}</dd>
                {% endfor %}
            </dl>
            <form method="POST" class="text-center">
                {% csrf_token %}
                {% if testrun.script_name == 'custom' %}
                    {{ stop_form }}
                    <button type="submit" name="action" value="stop" class="btn btn-primary">Stop</button>
                {% else %}
                    <button type="submit" name="action" value="reset" class="btn btn-danger">
                        <i class="icon-undo"></i> Reset {{ testrun.script_name }}
                    </button>
                    <button type="submit" name="action" value="stop" class="btn btn-warning">
                        <i class="icon-stop"></i> Stop {{ testrun.script_name }}
                    </button>
                {% endif %}
            </form>
        </div>
    </div>
{% endif %}
<table class="table table-bordered table-striped">
    <tr>
        <th>Status</th>
        <td>
            {% if testrun.scheduled %}
                <a class="btn btn-sm btn-primary pull-right"
                   href="{% url 'start_scheduled' testrun.pk %}">
                    Start
                </a>
            {% endif %}
            {{ testrun.status }}
        </td>
    </tr>
    <tr>
        <th>Created by</th>
        <td>{% firstof testrun.created_by.get_full_name testrun.created_by.username %}</td>
    </tr>
    <tr>
        <th>Created on</th>
        <td>{{ testrun.created_on }}</td>
    </tr>
    <tr>
        <th>Started on</th>
        <td data-run-start="{{ testrun.started_on.isoformat }}">{{ testrun.started_on }}</td>
    </tr>
    <tr>
        <th>Completed on</th>
        <td data-run-end="{{ testrun.completed_on.isoformat }}">{{ testrun.completed_on }}</td>
    </tr>
    <tr>
        <th>ETA</th>
        <td data-run-eta="{{ testrun.eta.isoformat }}">{{ testrun.eta }}</td>
    </tr>
    {% if user.is_authenticated %}
    <tr>
        <td colspan="2">
            <form action="{% url 'clone_run' %}" method="post" class="text-center clone">
                {% csrf_token %}
                <input type="hidden" value="{{ testrun.pk }}" name="run_id">
                {% if not testrun.waiting %}
                    <button type="submit" class="btn btn-inverse" value="reset" name="_submit">
                        <i class="icon-undo"></i> Reset
                    </button>
                {% endif %}
                <button type="submit" class="btn btn-inverse">
                    <i class="icon-copy"></i> Clone
                </button>
                {% if user.is_superuser %}
                    <a href="{% url 'admin:performance_testrun_change' testrun.pk %}" class="btn btn-danger">Admin</a>
                {% endif %}
            </form>
        </td>
    </tr>
    {% endif %}
</table>
<div class="panel panel-default">
    <div class="panel-heading"><h4 class="panel-title">Resources</h4></div>
    <div class="panel-body">
        <ol>
            {% for resource in testrun.resources.all %}
                <li>
                    <i class="{{ resource.status_icon }}"></i>
                    <a href="{{ resource.get_absolute_url }}">{{ resource.title }}</a>
                </li>
            {% endfor %}
        </ol>
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-heading"><h4 class="panel-title">Tags</h4></div>
    <div class="panel-body">
        {% for tag in testrun.tags.all %}
            <a class="btn btn-default" href="{% url 'tags' tag.slug %}">
                <i class="icon-tag"></i>
                {{ tag }}
            </a>
        {% endfor %}
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-heading"><h4 class="panel-title">Team</h4></div>
    <div class="panel-body">
        <ol>
            {% for member in testrun.team.all %}
                <li>{% firstof member.get_full_name member.username %}</li>
            {% empty %}
                <li>{{ testrun.created_by.get_full_name }}</li>
            {% endfor %}
        </ol>
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-heading"><h4 class="panel-title">Attachments</h4></div>
    <div class="panel-body">
        {% get_attachments_for testrun as "run_attachments" %}
        {% if run_attachments %}
            <ol>
                {% for attachment in run_attachments %}
                    <li>
                    <a href="{{ attachment.attachment_file.url }}">{{ attachment.filename }}</a>
                    </li>
                {% endfor %}
            </ol>
        {% endif %}
    </div>
    <div class="panel-footer">
        <div id="fine-uploader" class="pull-left"></div>
        <div class="clearfix"></div>
    </div>
</div>

performance/templates/performance/_script_result.html
{% if script_result %}
    {% include script_result %}
{% endif %}

performance/templates/performance/resource_detail.html
{% extends "base.html" %}
{% load markup_tags crispy_forms_tags %}
{% block title %}Resource: {{ resource.title }}{% endblock %}
{% block content %}
    <h1>
        <a href="{{ resource.get_absolute_url }}">{{ resource.title }}</a>
    </h1>
    <div class="tabbable">
        <ul class="nav nav-tabs">
            <li {% if not show_edit %}class="active"{% endif %}>
                <a href="#res-view" data-toggle="tab"><i class="icon-lightbulb"></i> View</a>
            </li>
            <li {% if show_edit %}class="active"{% endif %}>
                <a href="#res-edit" data-toggle="tab"><i class="icon-edit"></i> Edit</a>
            </li>
            <li>
                {% if user.is_superuser %}
                    <a href="{% url 'admin:performance_resource_change' resource.pk %}">Admin</a>
                {% endif %}
            </li>
        </ul>
        <div class="tab-content">
            <div id="res-view" class="tab-pane{% if not show_edit %} active{% endif %}">
                <div class="row">
                    <div class="col-lg-8">
                        <div class="panel panel-default">
                            <div class="panel-heading">Description</div>
                            <div class="panel-body">{{ resource.description|apply_markup:'markdown' }}</div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <table class="table table-bordered table-striped">
                            <tr>
                                <th>IP Address</th>
                                <td>{{ resource.ip_address }}</td>
                            </tr>
                            <tr>
                                <th>Type</th>
                                <td>{{ resource.rtype }}</td>
                            </tr>
                            <tr>
                                <th>Status</th>
                                <td>
                                    {{ resource.status }}
                                    <small class="text-muted" id="resource-status-{{ resource.pk }}">checking...</small>
                                </td>
                            </tr>
                        </table>
                    </div>
                </div>
                {% with run_list=resource.testrun_set.all %}
                    {% regroup run_list by status as run_by_status %}
                    {% include "performance/_run_nav.html" %}
                    {% include "performance/_run_tables.html" %}
                {% endwith %}
            </div>
            <div id="res-edit" class="tab-pane{% if show_edit %} active{% endif %}">
                <div class="row">
                    <div class="col-lg-12">
                        {% if user.is_authenticated %}
                            <div class="panel panel-default">
                                {% crispy edit_form %}
                            </div>
                        {% else %}
                            <p>Please <a href="{% url 'social:begin' 'google-oauth2' %}?next={{ request.path }}">login </a>to edit.</p>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block extrajs %}
    <script>
        $(function() {
            $('input#id_rtype').removeClass('form-control')
                .select2({tags:{{ types|safe }},
                          maximumSelectionSize:1,
                          width:'90%'})
        });
    </script>
{% endblock %}